#!/usr/bin/env ruby

$:.unshift File.join(File.expand_path(File.dirname(__FILE__)), 'lib')
require 'serializer'
require 'archiver'
require 'fileutils'

COPY_FILES = [
  'shaders',
  'tileset.png'
]

unless ARGV.size == 2
  puts "usage: mkdata <data dir> <out dir>"
  exit
end

data_dir = ARGV.shift
binary_dir = ARGV.shift

data_unpacked_dir = File.join(binary_dir, 'data_unpacked')
FileUtils.rm_rf(data_unpacked_dir)
FileUtils.mkpath(data_unpacked_dir)

COPY_FILES.each do |f|
  FileUtils.cp_r(File.join(data_dir, f), data_unpacked_dir)
end

Serializer.serialize_all(data_dir, binary_dir)
Archiver.run(binary_dir)
